// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteConfigDnspolicyHandlerFunc turns a function with the right signature into a delete config dnspolicy handler
type DeleteConfigDnspolicyHandlerFunc func(DeleteConfigDnspolicyParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteConfigDnspolicyHandlerFunc) Handle(params DeleteConfigDnspolicyParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteConfigDnspolicyHandler interface for that can handle valid delete config dnspolicy params
type DeleteConfigDnspolicyHandler interface {
	Handle(DeleteConfigDnspolicyParams, interface{}) middleware.Responder
}

// NewDeleteConfigDnspolicy creates a new http.Handler for the delete config dnspolicy operation
func NewDeleteConfigDnspolicy(ctx *middleware.Context, handler DeleteConfigDnspolicyHandler) *DeleteConfigDnspolicy {
	return &DeleteConfigDnspolicy{Context: ctx, Handler: handler}
}

/*
	DeleteConfigDnspolicy swagger:route DELETE /config/dnspolicy deleteConfigDnspolicy

# Delete a DNS policy

Delete the policy for a normalized domain suffix.
*/
type DeleteConfigDnspolicy struct {
	Context *middleware.Context
	Handler DeleteConfigDnspolicyHandler
}

func (o *DeleteConfigDnspolicy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteConfigDnspolicyParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
