// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// DeleteConfigDnspolicyNoContentCode is the HTTP code returned for type DeleteConfigDnspolicyNoContent
const DeleteConfigDnspolicyNoContentCode int = 204

/*
DeleteConfigDnspolicyNoContent OK

swagger:response deleteConfigDnspolicyNoContent
*/
type DeleteConfigDnspolicyNoContent struct {
}

// NewDeleteConfigDnspolicyNoContent creates DeleteConfigDnspolicyNoContent with default headers values
func NewDeleteConfigDnspolicyNoContent() *DeleteConfigDnspolicyNoContent {

	return &DeleteConfigDnspolicyNoContent{}
}

// WriteResponse to the client
func (o *DeleteConfigDnspolicyNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteConfigDnspolicyBadRequestCode is the HTTP code returned for type DeleteConfigDnspolicyBadRequest
const DeleteConfigDnspolicyBadRequestCode int = 400

/*
DeleteConfigDnspolicyBadRequest Malformed arguments for API call

swagger:response deleteConfigDnspolicyBadRequest
*/
type DeleteConfigDnspolicyBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigDnspolicyBadRequest creates DeleteConfigDnspolicyBadRequest with default headers values
func NewDeleteConfigDnspolicyBadRequest() *DeleteConfigDnspolicyBadRequest {

	return &DeleteConfigDnspolicyBadRequest{}
}

// WithPayload adds the payload to the delete config dnspolicy bad request response
func (o *DeleteConfigDnspolicyBadRequest) WithPayload(payload *models.Error) *DeleteConfigDnspolicyBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config dnspolicy bad request response
func (o *DeleteConfigDnspolicyBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigDnspolicyBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigDnspolicyNotFoundCode is the HTTP code returned for type DeleteConfigDnspolicyNotFound
const DeleteConfigDnspolicyNotFoundCode int = 404

/*
DeleteConfigDnspolicyNotFound DNS policy not found

swagger:response deleteConfigDnspolicyNotFound
*/
type DeleteConfigDnspolicyNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigDnspolicyNotFound creates DeleteConfigDnspolicyNotFound with default headers values
func NewDeleteConfigDnspolicyNotFound() *DeleteConfigDnspolicyNotFound {

	return &DeleteConfigDnspolicyNotFound{}
}

// WithPayload adds the payload to the delete config dnspolicy not found response
func (o *DeleteConfigDnspolicyNotFound) WithPayload(payload *models.Error) *DeleteConfigDnspolicyNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config dnspolicy not found response
func (o *DeleteConfigDnspolicyNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigDnspolicyNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteConfigDnspolicyInternalServerErrorCode is the HTTP code returned for type DeleteConfigDnspolicyInternalServerError
const DeleteConfigDnspolicyInternalServerErrorCode int = 500

/*
DeleteConfigDnspolicyInternalServerError Internal service error

swagger:response deleteConfigDnspolicyInternalServerError
*/
type DeleteConfigDnspolicyInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteConfigDnspolicyInternalServerError creates DeleteConfigDnspolicyInternalServerError with default headers values
func NewDeleteConfigDnspolicyInternalServerError() *DeleteConfigDnspolicyInternalServerError {

	return &DeleteConfigDnspolicyInternalServerError{}
}

// WithPayload adds the payload to the delete config dnspolicy internal server error response
func (o *DeleteConfigDnspolicyInternalServerError) WithPayload(payload *models.Error) *DeleteConfigDnspolicyInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete config dnspolicy internal server error response
func (o *DeleteConfigDnspolicyInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteConfigDnspolicyInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
