// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetConfigDnspolicyAllOKCode is the HTTP code returned for type GetConfigDnspolicyAllOK
const GetConfigDnspolicyAllOKCode int = 200

/*
GetConfigDnspolicyAllOK OK

swagger:response getConfigDnspolicyAllOK
*/
type GetConfigDnspolicyAllOK struct {

	/*
	  In: Body
	*/
	Payload *GetConfigDnspolicyAllOKBody `json:"body,omitempty"`
}

// NewGetConfigDnspolicyAllOK creates GetConfigDnspolicyAllOK with default headers values
func NewGetConfigDnspolicyAllOK() *GetConfigDnspolicyAllOK {

	return &GetConfigDnspolicyAllOK{}
}

// WithPayload adds the payload to the get config dnspolicy all o k response
func (o *GetConfigDnspolicyAllOK) WithPayload(payload *GetConfigDnspolicyAllOKBody) *GetConfigDnspolicyAllOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config dnspolicy all o k response
func (o *GetConfigDnspolicyAllOK) SetPayload(payload *GetConfigDnspolicyAllOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigDnspolicyAllOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigDnspolicyAllUnauthorizedCode is the HTTP code returned for type GetConfigDnspolicyAllUnauthorized
const GetConfigDnspolicyAllUnauthorizedCode int = 401

/*
GetConfigDnspolicyAllUnauthorized Invalid authentication credentials

swagger:response getConfigDnspolicyAllUnauthorized
*/
type GetConfigDnspolicyAllUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigDnspolicyAllUnauthorized creates GetConfigDnspolicyAllUnauthorized with default headers values
func NewGetConfigDnspolicyAllUnauthorized() *GetConfigDnspolicyAllUnauthorized {

	return &GetConfigDnspolicyAllUnauthorized{}
}

// WithPayload adds the payload to the get config dnspolicy all unauthorized response
func (o *GetConfigDnspolicyAllUnauthorized) WithPayload(payload *models.Error) *GetConfigDnspolicyAllUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config dnspolicy all unauthorized response
func (o *GetConfigDnspolicyAllUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigDnspolicyAllUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigDnspolicyAllInternalServerErrorCode is the HTTP code returned for type GetConfigDnspolicyAllInternalServerError
const GetConfigDnspolicyAllInternalServerErrorCode int = 500

/*
GetConfigDnspolicyAllInternalServerError Internal service error

swagger:response getConfigDnspolicyAllInternalServerError
*/
type GetConfigDnspolicyAllInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigDnspolicyAllInternalServerError creates GetConfigDnspolicyAllInternalServerError with default headers values
func NewGetConfigDnspolicyAllInternalServerError() *GetConfigDnspolicyAllInternalServerError {

	return &GetConfigDnspolicyAllInternalServerError{}
}

// WithPayload adds the payload to the get config dnspolicy all internal server error response
func (o *GetConfigDnspolicyAllInternalServerError) WithPayload(payload *models.Error) *GetConfigDnspolicyAllInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config dnspolicy all internal server error response
func (o *GetConfigDnspolicyAllInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigDnspolicyAllInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigDnspolicyAllServiceUnavailableCode is the HTTP code returned for type GetConfigDnspolicyAllServiceUnavailable
const GetConfigDnspolicyAllServiceUnavailableCode int = 503

/*
GetConfigDnspolicyAllServiceUnavailable Maintenance mode

swagger:response getConfigDnspolicyAllServiceUnavailable
*/
type GetConfigDnspolicyAllServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigDnspolicyAllServiceUnavailable creates GetConfigDnspolicyAllServiceUnavailable with default headers values
func NewGetConfigDnspolicyAllServiceUnavailable() *GetConfigDnspolicyAllServiceUnavailable {

	return &GetConfigDnspolicyAllServiceUnavailable{}
}

// WithPayload adds the payload to the get config dnspolicy all service unavailable response
func (o *GetConfigDnspolicyAllServiceUnavailable) WithPayload(payload *models.Error) *GetConfigDnspolicyAllServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config dnspolicy all service unavailable response
func (o *GetConfigDnspolicyAllServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigDnspolicyAllServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
