// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetConfigDnspolicyAllHandlerFunc turns a function with the right signature into a get config dnspolicy all handler
type GetConfigDnspolicyAllHandlerFunc func(GetConfigDnspolicyAllParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConfigDnspolicyAllHandlerFunc) Handle(params GetConfigDnspolicyAllParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetConfigDnspolicyAllHandler interface for that can handle valid get config dnspolicy all params
type GetConfigDnspolicyAllHandler interface {
	Handle(GetConfigDnspolicyAllParams, interface{}) middleware.Responder
}

// NewGetConfigDnspolicyAll creates a new http.Handler for the get config dnspolicy all operation
func NewGetConfigDnspolicyAll(ctx *middleware.Context, handler GetConfigDnspolicyAllHandler) *GetConfigDnspolicyAll {
	return &GetConfigDnspolicyAll{Context: ctx, Handler: handler}
}

/*
	GetConfigDnspolicyAll swagger:route GET /config/dnspolicy/all getConfigDnspolicyAll

# Get all DNS policies

Get all domain suffix policies and their traffic counters.
*/
type GetConfigDnspolicyAll struct {
	Context *middleware.Context
	Handler GetConfigDnspolicyAllHandler
}

func (o *GetConfigDnspolicyAll) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetConfigDnspolicyAllParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// GetConfigDnspolicyAllOKBody get config dnspolicy all o k body
//
// swagger:model GetConfigDnspolicyAllOKBody
type GetConfigDnspolicyAllOKBody struct {

	// dns policy attr
	DNSPolicyAttr []*models.DNSPolicyEntry `json:"dnsPolicyAttr"`
}

// Validate validates this get config dnspolicy all o k body
func (o *GetConfigDnspolicyAllOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDNSPolicyAttr(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetConfigDnspolicyAllOKBody) validateDNSPolicyAttr(formats strfmt.Registry) error {
	if swag.IsZero(o.DNSPolicyAttr) { // not required
		return nil
	}

	for i := 0; i < len(o.DNSPolicyAttr); i++ {
		if swag.IsZero(o.DNSPolicyAttr[i]) { // not required
			continue
		}

		if o.DNSPolicyAttr[i] != nil {
			if err := o.DNSPolicyAttr[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getConfigDnspolicyAllOK" + "." + "dnsPolicyAttr" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getConfigDnspolicyAllOK" + "." + "dnsPolicyAttr" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get config dnspolicy all o k body based on the context it is used
func (o *GetConfigDnspolicyAllOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateDNSPolicyAttr(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetConfigDnspolicyAllOKBody) contextValidateDNSPolicyAttr(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.DNSPolicyAttr); i++ {

		if o.DNSPolicyAttr[i] != nil {
			if err := o.DNSPolicyAttr[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("getConfigDnspolicyAllOK" + "." + "dnsPolicyAttr" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("getConfigDnspolicyAllOK" + "." + "dnsPolicyAttr" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *GetConfigDnspolicyAllOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetConfigDnspolicyAllOKBody) UnmarshalBinary(b []byte) error {
	var res GetConfigDnspolicyAllOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
