// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostConfigDnspolicyHandlerFunc turns a function with the right signature into a post config dnspolicy handler
type PostConfigDnspolicyHandlerFunc func(PostConfigDnspolicyParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostConfigDnspolicyHandlerFunc) Handle(params PostConfigDnspolicyParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostConfigDnspolicyHandler interface for that can handle valid post config dnspolicy params
type PostConfigDnspolicyHandler interface {
	Handle(PostConfigDnspolicyParams, interface{}) middleware.Responder
}

// NewPostConfigDnspolicy creates a new http.Handler for the post config dnspolicy operation
func NewPostConfigDnspolicy(ctx *middleware.Context, handler PostConfigDnspolicyHandler) *PostConfigDnspolicy {
	return &PostConfigDnspolicy{Context: ctx, Handler: handler}
}

/*
	PostConfigDnspolicy swagger:route POST /config/dnspolicy postConfigDnspolicy

# Create a DNS policy

Create an allow, drop, or trap policy for a domain suffix.
*/
type PostConfigDnspolicy struct {
	Context *middleware.Context
	Handler PostConfigDnspolicyHandler
}

func (o *PostConfigDnspolicy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostConfigDnspolicyParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
