// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PostConfigDnspolicyNoContentCode is the HTTP code returned for type PostConfigDnspolicyNoContent
const PostConfigDnspolicyNoContentCode int = 204

/*
PostConfigDnspolicyNoContent OK

swagger:response postConfigDnspolicyNoContent
*/
type PostConfigDnspolicyNoContent struct {
}

// NewPostConfigDnspolicyNoContent creates PostConfigDnspolicyNoContent with default headers values
func NewPostConfigDnspolicyNoContent() *PostConfigDnspolicyNoContent {

	return &PostConfigDnspolicyNoContent{}
}

// WriteResponse to the client
func (o *PostConfigDnspolicyNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PostConfigDnspolicyBadRequestCode is the HTTP code returned for type PostConfigDnspolicyBadRequest
const PostConfigDnspolicyBadRequestCode int = 400

/*
PostConfigDnspolicyBadRequest Malformed arguments for API call

swagger:response postConfigDnspolicyBadRequest
*/
type PostConfigDnspolicyBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigDnspolicyBadRequest creates PostConfigDnspolicyBadRequest with default headers values
func NewPostConfigDnspolicyBadRequest() *PostConfigDnspolicyBadRequest {

	return &PostConfigDnspolicyBadRequest{}
}

// WithPayload adds the payload to the post config dnspolicy bad request response
func (o *PostConfigDnspolicyBadRequest) WithPayload(payload *models.Error) *PostConfigDnspolicyBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config dnspolicy bad request response
func (o *PostConfigDnspolicyBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigDnspolicyBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigDnspolicyConflictCode is the HTTP code returned for type PostConfigDnspolicyConflict
const PostConfigDnspolicyConflictCode int = 409

/*
PostConfigDnspolicyConflict DNS policy already exists

swagger:response postConfigDnspolicyConflict
*/
type PostConfigDnspolicyConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigDnspolicyConflict creates PostConfigDnspolicyConflict with default headers values
func NewPostConfigDnspolicyConflict() *PostConfigDnspolicyConflict {

	return &PostConfigDnspolicyConflict{}
}

// WithPayload adds the payload to the post config dnspolicy conflict response
func (o *PostConfigDnspolicyConflict) WithPayload(payload *models.Error) *PostConfigDnspolicyConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config dnspolicy conflict response
func (o *PostConfigDnspolicyConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigDnspolicyConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigDnspolicyInternalServerErrorCode is the HTTP code returned for type PostConfigDnspolicyInternalServerError
const PostConfigDnspolicyInternalServerErrorCode int = 500

/*
PostConfigDnspolicyInternalServerError Internal service error

swagger:response postConfigDnspolicyInternalServerError
*/
type PostConfigDnspolicyInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigDnspolicyInternalServerError creates PostConfigDnspolicyInternalServerError with default headers values
func NewPostConfigDnspolicyInternalServerError() *PostConfigDnspolicyInternalServerError {

	return &PostConfigDnspolicyInternalServerError{}
}

// WithPayload adds the payload to the post config dnspolicy internal server error response
func (o *PostConfigDnspolicyInternalServerError) WithPayload(payload *models.Error) *PostConfigDnspolicyInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config dnspolicy internal server error response
func (o *PostConfigDnspolicyInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigDnspolicyInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
