// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DNSPolicyEntry DNS policy entry
//
// swagger:model DNSPolicyEntry
type DNSPolicyEntry struct {

	// Action applied to matching DNS queries
	// Required: true
	// Enum: [allow drop trap]
	Action *string `json:"action"`

	// Traffic counters formatted as packets:bytes
	// Read Only: true
	Counter string `json:"counter,omitempty"`

	// Domain suffix; matching is case-insensitive and includes subdomains
	// Required: true
	Domain *string `json:"domain"`
}

// Validate validates this DNS policy entry
func (m *DNSPolicyEntry) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDomain(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var dnsPolicyEntryTypeActionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["allow","drop","trap"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		dnsPolicyEntryTypeActionPropEnum = append(dnsPolicyEntryTypeActionPropEnum, v)
	}
}

const (

	// DNSPolicyEntryActionAllow captures enum value "allow"
	DNSPolicyEntryActionAllow string = "allow"

	// DNSPolicyEntryActionDrop captures enum value "drop"
	DNSPolicyEntryActionDrop string = "drop"

	// DNSPolicyEntryActionTrap captures enum value "trap"
	DNSPolicyEntryActionTrap string = "trap"
)

// prop value enum
func (m *DNSPolicyEntry) validateActionEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, dnsPolicyEntryTypeActionPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DNSPolicyEntry) validateAction(formats strfmt.Registry) error {

	if err := validate.Required("action", "body", m.Action); err != nil {
		return err
	}

	// value enum
	if err := m.validateActionEnum("action", "body", *m.Action); err != nil {
		return err
	}

	return nil
}

func (m *DNSPolicyEntry) validateDomain(formats strfmt.Registry) error {

	if err := validate.Required("domain", "body", m.Domain); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this DNS policy entry based on the context it is used
func (m *DNSPolicyEntry) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCounter(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DNSPolicyEntry) contextValidateCounter(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "counter", "body", string(m.Counter)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DNSPolicyEntry) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DNSPolicyEntry) UnmarshalBinary(b []byte) error {
	var res DNSPolicyEntry
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
